CREATE TABLE PRODUCTOS
(
  NOREG integer NOT NULL,
  FECHA date,
  DETALLE varchar(128),
  UNIDAD varchar(18),
  PRODUCTO varchar(18),
  CALCULO smallint,
  CANCELADO integer,
  RESTO smallint,
  TURNO smallint,
  TIPO_SESION smallint,
  NICK varchar(32),
  CODIGO_VENDEDOR varchar(36),
  RESPONSABLE varchar(128),
  LINK varchar(32),
  ULINK varchar(32),
  DUAL integer,
  FECHADETALLE varchar(75),
  CANTIDAD numeric(16,6),
  PC numeric(16,6),
  PV numeric(16,6),
  MONTO numeric(16,6),
  UNIDADPRODUCTO varchar(52),
  PU numeric(16,6),
  LIBROCONTABLE varchar(4),
  CUENTACONTABLE varchar(12),
  ESPRODUCTO smallint DEFAULT 1,
  MARCA varchar(128),
  TAMANIO varchar(16),
  PCUSD numeric(9,6),
  DESPLIEGUE smallint DEFAULT 0,
  TIPOISC smallint,
  TASAISC numeric(12,6),
  TIPODSCTO smallint,
  DSCTOUNIT numeric(12,6),
  TIPOCARGO smallint,
  CARGOUNIT numeric(12,6),
  TIPOOPERACION smallint,
  PR numeric(12,6),
  MINCOMPRA numeric(12,6),
  FECHAVENCIMIENTO date,
  VERSION_IMG smallint,
  SERIE varchar(5),
  CODIGOSUNAT varchar(10),
  AFECTOICBPER smallint,
  UBICACION varchar(64),
  PESO numeric(12,2),
  PMAYOR numeric(12,4),
  STOCKMINIMO numeric(12,4),
  ESTADOSERVPROD smallint DEFAULT 0,
  FACTURABLE smallint DEFAULT 0,
  PERECIBLE smallint DEFAULT 0,
  CLASIFICADOR varchar(16),
  RECETA smallint DEFAULT 0,
  NROLOTE varchar(32),
  PRESENTACION varchar(64),
  CONSTRAINT INTEG_203 PRIMARY KEY (NOREG)
);